name 'Analytical Labs-osqa'
version '1.0'

author 'Tom Barber'
license ''
project_page ''
source ''
summary ''
description ''
dependency 'Analytical Labs/apache', '==1.0'
dependency 'Analytical Labs/mysql', '==1.0'
